sfdc:
  auth:
    host: "login.salesforce.com"
    username: "jeferson.rgomes@hotmail.com"
    password: "JeRiGo852060!@#$"
    security_token: "nmbJK6ijrHf5gIqncf8Wouqy"
    password_and_token: "JeRiGo852060!@#$nmbJK6ijrHf5gIqncf8Wouqy"
    client_id: "3MVG9Xl3BC6VHB.bF7yQiSiCEdRHA3n.9C_X_WSRDNTKTLGFDzAI2MpkQdHc7b.13_IhjWSCxWgNVsoHcC1RN"
    client_secret: "7BB9A1C4FEE0319760B9493D955D3AF8848B2F0CE44B34E1F292FEA7BF769E5B"
  endpoint:
    host: "dhp000002lnpoma0-dev-ed.develop.my.salesforce.com"
    version: "v51.0"
    basepath: "/services/data/"
    path: 
      insert: "/sobjects/"
      consult: "/query/"

    