#%RAML 1.0
title: Demonstração de utilização de componentes no curso Udemy Integracao SalesForce
  
/demo-component-01:
  get:
  
/demo-component-02:
  post:
  
/demo-component-03:
  post:
  
/demo-component-04:
  post:
  
/demo-component-05:
  get: