#%RAML 1.0
title: API Curso Udemy Integracao SalesForce

/api-health:
  get:
  
/demo-01:
  /rest:
    get:
    
  /soap:
    get:
    
/demo-02:
  /inserir:
    post:    

/demo-03:
  /consultar:
    get: